# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # 使用 ldflags="-s -w" 去掉符号表和调试信息，以减少发布包的大小
    ldflags:
      - -s
      - -w
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    main: .
archives:
  - id: default
    builds:
      - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: KusionStack
    name: kusion
  draft: false
  header: |
    ## Docker Images
    * `kusionstack/kusion:{{ .Env.KUSION_VERSION }}`
    
    ## Dependent version
    * [kclvm-go](https://github.com/KusionStack/kclvm-go): `{{ .Env.KCLVM_GO_VERSION }}`
    * [kcl-plugin](https://github.com/KusionStack/kcl-plugin): `{{ .Env.KCL_PLUGIN_VERSION }}`

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - kusionstack/{{ .ProjectName }}:{{ .Tag }}-amd64
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

docker_manifests:
  - use: docker
    name_template: kusionstack/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - kusionstack/{{ .ProjectName }}:{{ .Tag }}-amd64
  - use: docker
    name_template:  kusionstack/{{ .ProjectName }}:latest
    image_templates:
      - kusionstack/{{ .ProjectName }}:{{ .Tag }}-amd64

brews:
  - tap:
      owner: KusionStack
      name: homebrew-tap
    url_template: "https://github.com/KusionStack/kusion/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: GoReleaser Bot
      email: goreleaser@carlosbecker.com
    folder: HomebrewFormula
    homepage: "https://github.com/KusionStack/kusion"
    description: "Codify and deliver intentions to Kubernetes and Clouds"
    license: "Apache License"
    skip_upload: false
    test: |
      system "#{bin}/kusion version"
