import catalog.models.schema.v1 as ac
import catalog.models.schema.v1.workload as wl
import catalog.models.schema.v1.workload.network as n
import catalog.models.schema.v1.workload.container as c

{{ .AppName }}: ac.AppConfiguration {
    workload: wl.Service {
        containers: {
            "{{ .AppName }}": c.Container {
                image = "{{ .Image }}"
                resources: {
                    "cpu": "500m"
                    "memory": "512Mi"
                }
            }
        }
        replicas: 1
        ports: [
            n.Port {
                port: 80
            }
        ]
    }
}
