// Auto generated by 'go run gen.go', DO NOT EDIT.

package version

func init() {
	info = &Info{
		ReleaseVersion: "v0.7.3",
		GitInfo: &GitInfo{
			LatestTag: "v0.7.3",
			Commit:    "785fcd04b306741497f2c0fe7a18db3f1b46ac2d",
			TreeState: "clean",
		},
		BuildInfo: &BuildInfo{
			GoVersion: "go1.19.3",
			GOOS:      "darwin",
			GOARCH:    "amd64",
			NumCPU:    12,
			Compiler:  "gc",
			BuildTime: "2023-01-09 11:33:24",
		},
		Dependency: &DependencyVersion{
			KclvmgoVersion:   "v0.4.4-beta.2",
			KclPluginVersion: "v0.4.1-alpha2",
		},
	}
}
