name: Test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  Publish: # Pack and publish image to Docker Hub and Github Release
    runs-on: ubuntu-latest
    needs: [Test, Lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # <--- Build and Package --->
      - name: Pack kusion release packages for multiple platforms
        env:
          GO111MODULE: on
        run: make build-all
      # <--- Get version informations --->
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=kusion_version::$(./_build/bundles/kusion-linux/bin/kusion version -s | cut -d ';' -f 1)"
          echo "::set-output name=kclvmgo_version::$(./_build/bundles/kusion-linux/bin/kusion version -y | grep kclvmgoVersion | cut -d ':' -f 2 | awk '$1=$1')"
          echo "::set-output name=kclplugin_version::$(./_build/bundles/kusion-linux/bin/kusion version -y | grep kclPluginVersion | cut -d ':' -f 2 | awk '$1=$1')"
      # <--- Login, build and push image to Docker Hub --->
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push image to Docker Hub
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: kusionstack/kusion:latest,kusionstack/kusion:${{ steps.get_version.outputs.kusion_version }}
      - name: Build and push kusionctl image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_kusionctl
          push: true
          tags: kusionstack/kusionctl:latest,kusionstack/kusionctl:${{ steps.get_version.outputs.kusion_version }}
      # <--- Push kusion big packages for multiple platforms to Github Release --->
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true
      #     files: ./_build/bundles/*.tgz*
      #     append_body: true
      #     body: |
      #       ## Docker Images
      #       * `kusionstack/kusion:${{ steps.get_version.outputs.kusion_version }}`

      #       ## Dependent version
      #       * [kclvm-go](https://github.com/KusionStack/kclvm-go): `${{ steps.get_version.outputs.kclvmgo_version }}`
      #       * [kcl-plugin](https://github.com/KusionStack/kcl-plugin): `${{ steps.get_version.outputs.kclplugin_version }}`
      # <--- End --->